name: Deploy to GitHub pages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate static files
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn run build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist/
          git init
          echo 'rieg.me' > CNAME
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: ./dist
          force: true
